### ISSUE TITLE
a1 - write test case

### ISSUE THREAD

**Issue by rickyzhangca** [rickyzhangca/CISC-327#5]

**Comment by rickyzhangca** [comment]
- [ ] register

**Comment by QiruJin** [comment]
sell & buy

**Comment by cherishfan0320** [comment]
- [ ] landing & update & exit

**Comment by chengzhen-guo** [comment]
- [ ] Login & Logout

**Comment by QiruJin** [comment]
- [ ] sell & buy

**Comment by rickyzhangca** [comment]
example @cherishfan0320 @chengzhen-guo @QiruJin 
| Specification                              | Test ID | Purpose                                                        | Test Procedure                        | Expect Output                                                    |
|--------------------------------------------|---------|----------------------------------------------------------------|---------------------------------------|------------------------------------------------------------------|
| Command invalid if the user has logged in. | R2.1.1  | Check if `register` command is invalid when user has logged in | `login, tester, tester1234, register` | "Logged in successfully. Invalid command when user is logged in" |

**Comment by rickyzhangca** [comment]
accidentally closed, reopening

**Comment by rickyzhangca** [comment]
done
